name: Gradle Test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $protected-branches ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          cache: 'gradle'
          check-latest: true
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
      
      - name: Run test task
        run: ./gradlew test --no-daemon
      
      - name: Upload reports artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: build/reports/tests/test/
      
