name: Fast forward

on:
  workflow_call: {}

jobs:
  check_fast_forward:
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
    - name: Check fast forward is possible
      uses: sequoia-pgp/fast-forward@v1
      with:
        merge: false
        comment: always
  fast_forward:
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request && github.event.comment.body == '/fast-forward' }}
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
    - name: Fast forward and merge
      uses: sequoia-pgp/fast-forward@v1
      with:
        merge: true
        comment: on-error
        