name: Fast forward

on:
  pull_request:
    branches:
    - $default-branch
    types:
    - opened
    - reopened
    - synchronize
  issue_comment:
    types:
    - created

jobs:
  call:
    uses: ideal-state/.github/workflows/fast-forward.yml@master
        